name: Hugo build for GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # for Hugo themes
          fetch-depth: 0  # TODO: justify

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Create Pages artifact
        uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: public/


  publish:
    needs: build

    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}  # TODO: redundant?

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write  # deploy to Pages
      id-token: write  # TODO

    steps:
      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v1
